### ISSUE TITLE
AutoPlug freezes after failed plugin download.

### ISSUE THREAD

**Issue by ablac** [Osiris-Team/AutoPlug-Plugin#4]
This just happened to me with ProtocoLib.Jar I was on 4.5.0 and AutoPlug tried to download, it failed to download, and then froze after that. and just sat there for 20 min, until I finally just shutdown the box.

There was No error codes or messages out of the ordinary. It just failed to download the file and then told me to download it manually. and even gave me the working link.

**Comment by Osiris-Team** [comment]
I reproduced the error and got following:
java.nio.file.NoSuchFileException: C:\Users\osiris\AppData\Local\Temp\htmlunit997839408003989525.tmp
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
        at java.nio.file.Files.newInputStream(Unknown Source)
        at com.gargoylesoftware.htmlunit.DownloadedContent$OnFile.getInputStream(DownloadedContent.java:89)
        at com.gargoylesoftware.htmlunit.WebResponseData.getStream(WebResponseData.java:98)
        at com.gargoylesoftware.htmlunit.WebResponseData.getInputStream(WebResponseData.java:205)
        at com.gargoylesoftware.htmlunit.WebResponse.getContentAsStream(WebResponse.java:274)
        at com.osiris.autoplug.client.managers.DownloadManager.downloadJar(DownloadManager.java:84)
        at com.osiris.autoplug.client.online.Communication.downloadUpdate(Communication.java:387)
        at com.osiris.autoplug.client.online.Communication.checkForUpdates(Communication.java:242)
        at com.osiris.autoplug.client.online.Communication.listen(Communication.java:103)
        at com.osiris.autoplug.client.online.Communication.<init>(Communication.java:62)
        at com.osiris.autoplug.client.Main.main(Main.java:99)

**Comment by Osiris-Team** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Download error with ProtocolLib](https://trello.com/c/lsOS75Ms/111-download-error-with-protocollib)

**Comment by Osiris-Team** [comment]
Fixed in v.0.8
